---
name: blue7
description: Winblues 7

base-image: ghcr.io/ublue-os/bazzite-dx-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: dnf
    install:
      packages:
      - kvantum

  - type: script
    snippets:
      - 'cd $CONFIG_DIRECTORY/scripts && for script in *.sh; do [ -f "$script" ] && bash "$script" || exit $?; done'

  - type: signing

