---
name: blue7
description: Winblues 7

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: dnf
    install:
      packages:
      - https://github.com/winblues/blue7/releases/download/aerothemeplasma-0-0.1.20250423git3c2990e.fc42/aerothemeplasma-0-0.1.20250423git3c2990e.fc42.x86_64.rpm

  - type: script
    snippets:
      - 'cd $CONFIG_DIRECTORY/scripts && for script in *.sh; do [ -f "$script" ] && bash "$script"; done'

  - type: signing

