---
name: blue7
description: Winblues 7

base-image: ghcr.io/ublue-os/aurora-dx
image-version: stable-daily

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: rpm-ostree
    install:
      - neovim

  - type: script
    snippets:
      - 'cd $CONFIG_DIRECTORY/scripts && for script in *.sh; do [ -f "$script" ] && bash "$script"; done'

  - type: signing

